version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    restart: always
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: decentralot_indexer
      MONGO_INITDB_ROOT_PASSWORD: decentralot_indexer_password
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

  socituri_backend:
    container_name: backend
    restart: always
    environment:
      DB_HOST: mongodb_container
      DB_PORT: 27017
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3010:3010
    
volumes:
  mongodb_data_container:
