[package]
name = "decentralot"
version = "0.1.0"

[dependencies]
Sui = { local = "/home/andreas/Documents/socituri/Socituri_Decentralot/move/sui/crates/sui-framework/packages/sui-framework" }

[addresses]
decentralot = "0x0"
team = "0xdb2866f06da05f8426817810ac01f13104d6bf289cee0669e945ebf2e785b5e6"
